app = "mks-redis-35"

[build]
image = "flyio/redis:6.2.6"

[[mounts]]
destination = "/data"
source = "mks_redis_store"

[[services]]
internal_port = 6_379
protocol = "tcp"

  [[services.ports]]
  port = 10_000

  [[services.tcp_checks]]
  interval = "10s"
  timeout = "2s"
